image: docker:19.03.12

pipelines:
  services:
    docker:
      memory: 2048

  branches:
    development:
      - step:
          name: Build and Push to ECR - QA for WalletServiceApi
          deployment: QA
          services:
            - docker
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION='us-east-1'
            - export ECR_REPO_URI=948104088074.dkr.ecr.us-east-1.amazonaws.com/walletserviceapi
            - export IMAGE_TAG=qa-$BITBUCKET_COMMIT
            - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
            - docker push $ECR_REPO_URI:$IMAGE_TAG
            - sed -i "s|948104088074.dkr.ecr.us-east-1.amazonaws.com/walletserviceapi:tag|$ECR_REPO_URI:$IMAGE_TAG|g" qa-task-definition.json
            - aws ecs register-task-definition --cli-input-json file://qa-task-definition.json
            - aws ecs update-service --cluster HeroSystemQA --service WalletServiceApi --task-definition WalletServiceApiTaskFamily --force-new-deployment

    master:
      - step:
          name: Build and Push to ECR - Prod for WalletServiceApi
          deployment: Production
          services:
            - docker
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - export AWS_DEFAULT_REGION='us-east-1'
            - export ECR_REPO_URI=948104088074.dkr.ecr.us-east-1.amazonaws.com/walletserviceapi
            - export IMAGE_TAG=prod-$BITBUCKET_COMMIT
            - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
            - docker push $ECR_REPO_URI:$IMAGE_TAG
            - sed -i "s|<IMAGE_NAME>|$ECR_REPO_URI:$IMAGE_TAG|g" prod-task-definition.json
            - aws ecs register-task-definition --cli-input-json file://prod-task-definition.json
            - aws ecs update-service --cluster HeroSystemProd --service WalletServiceApiProd --task-definition WalletServiceApiTaskFamily --force-new-deployment
